### ISSUE TITLE
ImportError: libtcl8.5.so

### ISSUE THREAD

**Issue by Amrithasuresh** [rougier/ten-rules#2]
I tried the first example 'figure-1.py' in Ubuntu 16.04. I got the error like below

'**ImportError: libtcl8.5.so: cannot open shared object file: No such file or directory**'.

After installing this package '**sudo apt-get install tcl8.5-dev tk8.5-dev**'. The required library was installed. 

It solved the 'ImportError'.

Perhaps this will help someone.

**Comment by rougier** [comment]
I imagine this is related to your matplotlib installation.
